CREATE TABLE EMP_1 (
EMP_NUM NUMERIC(3,0) PRIMARY KEY,
EMP_LNAME VARCHAR(15) NOT NULL,
EMP_FNAME VARCHAR(15) NOT NULL,
EMP_INITIAL CHAR(1),
EMP_HIREDATE DATE,
JOB_CODE NUMERIC(3,0) REFERENCES JOB (JOB_CODE)
);