CREATE OR REPLACE FUNCTION trigger_func_updatecust_balance()
	RETURNS TRIGGER
	LANGUAGE PLPGSQL
AS $$
BEGIN
	UPDATE CUSTOMER
	SET CUST_BALANCE = CUST_BALANCE + NEW.INV_AMOUNT
	FROM INVOICE
	WHERE CUSTOMER.CUST_NUM = NEW.CUST_NUM;
	RAISE NOTICE 'trg_updatecustbalance was triggered';
	RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_updatecustbalance
BEFORE INSERT ON INVOICE
FOR EACH ROW
EXECUTE PROCEDURE trigger_func_updatecust_balance();
