CREATE OR REPLACE PROCEDURE prc_cust_add (
	NUM CUSTOMER.CUST_NUM%TYPE,
	FNAME CUSTOMER.CUST_FNAME%TYPE,
	LNAME CUSTOMER.CUST_LNAME%TYPE,
	BALANCE CUSTOMER.CUST_BALANCE%TYPE)
LANGUAGE SQL
AS $$
INSERT INTO CUSTOMER VALUES (NUM, LNAME, FNAME, BALANCE)
$$;