CREATE OR REPLACE PROCEDURE prc_invoice_add (
	INV_NUM INVOICE.INV_NUM%TYPE,
	CUST_NUM INVOICE.INV_NUM%TYPE,
	INV_DATE INVOICE.INV_DATE%TYPE,
	INV_AMOUNT INVOICE.INV_AMOUNT%TYPE)
LANGUAGE SQL
AS $$
INSERT INTO INVOICE VALUES (INV_NUM, CUST_NUM, INV_DATE, INV_AMOUNT)
$$;