CREATE OR REPLACE FUNCTION trigger_func_linez_total()
	RETURNS TRIGGER
	LANGUAGE PLPGSQL
AS $$
BEGIN
	UPDATE LINEZ
	SET LINE_TOTAL =  NEW.LINE_UNITS * NEW.LINE_PRICE
	WHERE INV_NUMBER = NEW.INV_NUMBER AND LINE_NUMBER = NEW.LINE_NUMBER;
	RAISE NOTICE 'trg_linez_total was triggered';
	RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_linez_total
AFTER INSERT OR UPDATE OF LINE_UNITS, LINE_PRICE ON LINEZ
FOR EACH ROW
EXECUTE PROCEDURE trigger_func_linez_total();