CREATE OR REPLACE PROCEDURE prc_cus_balance_update (
	NUM INVOICEZ.INV_NUMBER%TYPE)
LANGUAGE PLPGSQL
AS $$
DECLARE 
	TOTINV INVOICEZ.INV_TOTAL%TYPE;
BEGIN
	SELECT INV_TOTAL INTO TOTINV FROM INVOICEZ WHERE INV_NUMBER = NUM;
	UPDATE CUSTOMER
	SET CUS_BALANCE = CUS_BALANCE + TOTINV
	WHERE CUSTOMER.CUS_CODE = (SELECT CUS_CODE FROM INVOICEZ WHERE INV_NUMBER = NUM);
END;
$$;