ALTER TABLE MODEL
ADD COLUMN MOD_WAIT_CHG NUMERIC(6,2);

UPDATE MODEL
SET MOD_WAIT_CHG = 100
WHERE MOD_CODE = 'C-90A';

UPDATE MODEL
SET MOD_WAIT_CHG = 50
WHERE MOD_CODE = 'PA23-250';

UPDATE MODEL
SET MOD_WAIT_CHG = 75
WHERE MOD_CODE = 'PA31-350';