ALTER TABLE CHARTER
ADD COLUMN CHAR_WAIT_CHG NUMERIC(6,2);

ALTER TABLE CHARTER
ADD COLUMN CHAR_FLT_CHG_HR NUMERIC(6,2);

ALTER TABLE CHARTER
ADD COLUMN CHAR_FLT_CHG NUMERIC(6,2);

ALTER TABLE CHARTER
ADD COLUMN CHAR_TAX_CHG NUMERIC(6,2);

ALTER TABLE CHARTER
ADD COLUMN CHAR_TOT_CHG NUMERIC(6,2);

ALTER TABLE CHARTER
ADD COLUMN CHAR_PYMT_CHG NUMERIC(6,2);

ALTER TABLE CHARTER
ADD COLUMN CHAR_BALANCE NUMERIC(6,2);