CREATE OR REPLACE FUNCTION trg_func_char_hours()
	RETURNS TRIGGER
	LANGUAGE PLPGSQL
AS $$
BEGIN
	CASE TG_OP
	WHEN 'INSERT' THEN
		UPDATE AIRCRAFT
		SET AC_TTAF = AC_TTAF + NEW.CHAR_HOURS_FLOWN,
		 	AC_TTEL = AC_TTEL + NEW.CHAR_HOURS_FLOWN,
		 	AC_TTER = AC_TTER + NEW.CHAR_HOURS_FLOWN;
		RAISE NOTICE 'trg_char_hours was triggered - ON INSERT';
	WHEN 'DELETE' THEN
		UPDATE AIRCRAFT
		SET AC_TTAF = AC_TTAF - OLD.CHAR_HOURS_FLOWN,
			AC_TTEL = AC_TTEL - OLD.CHAR_HOURS_FLOWN,
			AC_TTER = AC_TTER - OLD.CHAR_HOURS_FLOWN;
		RAISE NOTICE 'trg_char_hours was triggered - ON DELETE';
	ELSE
      	RAISE EXCEPTION 'This trigger function expects INSERT or UPDATE!';
	END CASE;
	RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_char_hours
AFTER INSERT OR DELETE ON CHARTER
FOR EACH ROW
EXECUTE PROCEDURE trg_func_char_hours();