CREATE OR REPLACE FUNCTION trg_func_pic_hours()
	RETURNS TRIGGER
	LANGUAGE PLPGSQL
AS $$
BEGIN
	CASE TG_OP
	WHEN 'INSERT' THEN
		IF NEW.CREW_JOB = 'Pilot' THEN
			UPDATE PILOT
			SET PIL_PIC_HRS = PIL_PIC_HRS + CHAR_HOURS_FLOWN
			FROM CHARTER
			WHERE CHARTER.CHAR_TRIP = NEW.CHAR_TRIP AND EMP_NUM = NEW.EMP_NUM;
			RAISE NOTICE 'trg_pic_hours was triggered - ON INSERT';
		END IF;
	WHEN 'DELETE' THEN
		IF OLD.CREW_JOB = 'Pilot' THEN
			UPDATE PILOT
			SET PIL_PIC_HRS = PIL_PIC_HRS - CHAR_HOURS_FLOWN
			FROM CHARTER
			WHERE CHARTER.CHAR_TRIP = OLD.CHAR_TRIP AND EMP_NUM = OLD.EMP_NUM;
			RAISE NOTICE 'trg_pic_hours was triggered - ON DELETE';
		END IF;
	ELSE
      	RAISE EXCEPTION 'This trigger function expects INSERT or UPDATE!';
	END CASE;
	RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_pic_hours
AFTER INSERT OR DELETE ON CREW
FOR EACH ROW
EXECUTE PROCEDURE trg_func_pic_hours();