ALTER TABLE DETAILRENTAL
ALTER COLUMN DETAIL_RETURNDATE TYPE TIMESTAMP ('YYYY-MM-DD HH12:MI:SS AM');

UPDATE DETAILRENTAL
SET DETAIL_RETURNDATE = DETAIL_RETURNDATE + INTERVAL '10H'
		WHERE RENT_NUM = 1001 AND VID_NUM IN (34342, 34366);

UPDATE DETAILRENTAL
SET DETAIL_RETURNDATE = DETAIL_RETURNDATE + INTERVAL '11H30M'
		WHERE RENT_NUM = 1001 AND VID_NUM IN (61353);

UPDATE DETAILRENTAL
SET DETAIL_RETURNDATE = DETAIL_RETURNDATE + INTERVAL '15H30'
		WHERE RENT_NUM = 1002 AND VID_NUM IN (59237);

UPDATE DETAILRENTAL
SET DETAIL_RETURNDATE = DETAIL_RETURNDATE + INTERVAL '16H'
		WHERE RENT_NUM = 1003;

UPDATE DETAILRENTAL
SET DETAIL_RETURNDATE = DETAIL_RETURNDATE + INTERVAL '9H'
		WHERE RENT_NUM = 1004;

UPDATE DETAILRENTAL
SET DETAIL_RETURNDATE = DETAIL_RETURNDATE + INTERVAL '12H30M'
		WHERE RENT_NUM = 1005;

UPDATE DETAILRENTAL
SET DETAIL_RETURNDATE = DETAIL_RETURNDATE + INTERVAL '22H15M'
		WHERE RENT_NUM = 1006 AND VID_NUM IN (34366),

UPDATE DETAILRENTAL
SET DETAIL_RETURNDATE = DETAIL_RETURNDATE + INTERVAL '21H30M'
		WHERE RENT_NUM = 1008;