CREATE TABLE BUFFER_RENTDAYS (
PRICE_CODE INTEGER,
PRICE_RENTDAYS NUMERIC(2,0)
);

INSERT INTO BUFFER_RENTDAYS VALUES
	(1, 5),
	(2, 3),
	(3, 5),
	(4, 7);

UPDATE PRICE
SET PRICE_RENTDAYS = BUFFER_RENTDAYS.PRICE_RENTDAYS
FROM BUFFER_RENTDAYS
WHERE PRICE.PRICE_CODE = BUFFER_RENTDAYS.PRICE_CODE;

DROP TABLE BUFFER_RENTDAYS;