CREATE OR REPLACE FUNCTION trg_func_mem_balance()
	RETURNS TRIGGER
	LANGUAGE PLPGSQL
AS $$

DECLARE
	LATEFEE1 NUMERIC(4,1) := old.DETAIL_DAYS_LATE * old.DETAIL_DAILYLATEFEE;
	LATEFEE2 NUMERIC(4,1) := new.DETAIL_DAYS_LATE * new.DETAIL_DAILYLATEFEE;
	FEEDIFF NUMERIC(4,1);

BEGIN
	IF LATEFEE1 IS NULL THEN
		LATEFEE1 := 0;
	ELSIF LATEFEE2 IS NULL THEN
		LATEFEE2 := 0;
	END IF;

	FEEDIFF := LATEFEE2 - LATEFEE1;

	IF FEEDIFF <> 0 THEN
		UPDATE MEMBERSHIP
		SET MEM_BALANCE = MEM_BALANCE + FEEDIFF
		FROM RENTAL
		WHERE MEMBERSHIP.MEM_NUM = (SELECT MEM_NUM FROM RENTAL WHERE new.RENT_NUM = RENTAL.RENT_NUM);
	END IF;

	RAISE NOTICE 'trg_mem_balance was triggered - fee difference = %', FEEDIFF;


	RETURN NEW;
END; 
$$;

CREATE OR REPLACE TRIGGER trg_mem_balance
AFTER UPDATE OF DETAIL_DUEDATE, DETAIL_RETURNDATE
ON DETAILRENTAL
FOR EACH ROW
EXECUTE PROCEDURE trg_func_mem_balance();