CREATE OR REPLACE PROCEDURE prc_new_rental(
	NUM RENTAL.MEM_NUM%TYPE)
LANGUAGE PLPGSQL
AS $$
DECLARE
IS_MEM NUMERIC(1,0) := (SELECT COUNT(MEM_NUM) FROM MEMBERSHIP WHERE MEM_NUM = NUM);

BEGIN

	IF IS_MEM = 0 THEN
		RAISE NOTICE 'ERROR -> The membership number % does not exist.', NUM;
	ELSE
		RAISE NOTICE 'Previous balance: $%', (SELECT MEM_BALANCE FROM MEMBERSHIP WHERE MEM_NUM = NUM);
		INSERT INTO RENTAL VALUES (nextval('rent_num_seq'), CURRENT_DATE, NUM);
	END IF;
END;
$$;